# FROM node:latest as node
# LABEL author="Christiyan Velkov"
# WORKDIR /app
# COPY . .
# RUN npm install
# RUN npm run build --prod

# stage 2
FROM nginx:alpine
COPY  /dist/christiyan-progress-task/usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]